### PR TITLE
Fix follower hit-testing (Resolves #7)

### LINKED ISSUE #7: Implement hit testing for Followers
The `Follower` widget positions itself as desired, but hit testing doesn't work. Configure the hit testing in the render object to behave like a traditional widget.

### PR DESCRIPTION
**Pull request by angelosilvestre**
Fix follower hit-testing. Resolves #7 

Hit-testing the follower wasn't working correctly. The follower offset wasn't being considered.

This PR changes the hit-testing to apply the offset to the transform.

I also found a bug where the follower wasn't being painted until the screen was resized or the leader was dragged. I'm not sure if this fix could cause problems.

### CODE REVIEW

File: lib/src/follower.dart [hunk 1]
```diff
@@ -258,6 +260,13 @@ class RenderFollowerLayer extends RenderProxyBox {
 
     if (!link.leaderConnected && _previousFollowerOffset == null) {
       print("The leader isn't connected and there's no cached offset. Not painting anything.");
+      // In the first frame we are not connected to the leader.
+      // Check again in the next frame.
+      WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
```
Comment (matthew-carroll) [inline lib/src/follower.dart:265]: Is there another signal that we could use for this purpose? It's possible that we're never linked, which would result in continuous paint requests for no reason....

File: lib/src/follower.dart [hunk 2]
```diff
@@ -241,8 +240,11 @@ class RenderFollowerLayer extends RenderProxyBox {
 
   @override
   bool hitTestChildren(BoxHitTestResult result, {required Offset position}) {
+    final followerOffset = _previousFollowerOffset ?? Offset.zero;
+    final transform = layer?.getLastTransform()?..translate(followerOffset.dx, followerOffset.dy);
```
Comment (matthew-carroll) [inline lib/src/follower.dart:244]: I see that we're accessing the "transform" of layer. Can that transform include a rotation? If so, it would seem that we need to figure out how the `followeOffset` maps to that transformed space.

File: lib/src/follower.dart (hunk 1 above)
Comment (angelosilvestre) [reply lib/src/follower.dart:276]: Updated.

File: lib/src/follower.dart (hunk 2 above)
Comment (angelosilvestre) [reply lib/src/follower.dart:245]: The transform could include a rotation, but it doesn't seem we are applying rotation at any place.

Comment (matthew-carroll) [reply lib/src/follower.dart:245]: Ok. We can leave this as-is for now. We might run into issues when widgets are rotated. We'll see.

File: lib/src/follower.dart (hunk 1 above)
Comment (matthew-carroll) [reply lib/src/follower.dart:276]: This still seems fragile and overly specific. I see that I copied the implementation of `LayerLInk`, which means we can change it. Would this problem be solved by having `LayerLink` notify listeners when a leader is connected or disconnected?

Comment (angelosilvestre) [reply lib/src/follower.dart:276]: It seems that we are constantly changing from connected to disconnected. With this change, the test timed out. Relevant code:

```dart
set leader(CustomLeaderLayer? value) {
    if (value == _leader) {
      return;
    }
    final previousLeaderConnected = leaderConnected;
    _leader = value;
    if (leaderConnected != previousLeaderConnected) {
      notifyListeners();
    }
  }
```

Comment (matthew-carroll) [reply lib/src/follower.dart:276]: Can you try to found out why we're switching from connected to disconnected? This sounds like a bug that we should fix.

Comment (angelosilvestre) [reply lib/src/follower.dart:276]: This is only happening with the new code with a listener. In the `Leader` paint method, when we call `pushLayer` it causes `detach` and `attach` to be called on the `CustomLeaderLayer`. These methods update the `leader` in the `LayerLink`, which notifies the listener again...

Comment (angelosilvestre) [reply lib/src/follower.dart:276]: Unfortunately, It doesn't seem that we have a way to avoid that.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you fix the conflicts that were just introduced by merging the log changes?

**Comment by angelosilvestre** [comment]
@matthew-carroll Done.

**Review by matthew-carroll — APPROVED** [review]
LGTM
